swagger: "2.0"
info:
  description: "This is a sample rest service"
  version: "1.0.0"
  title: "My first Service"
  
host: "localhost"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://someURL"

schemes:
- "https"
- "http"
paths:
  /pet/pets:
    get:
      tags:
      - "pet"
      summary: "Gets All Pets"
      description: "Gets all the pets"
      operationId: "findPetsByStatus"
      produces:
      - "application/json"
      
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
        400:
          description: "Invalid status value"
      
  

definitions:
  
  Pet:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Pet"
  
